### ISSUE TITLE
failure on emacs configure script

### ISSUE THREAD

**Issue by ezrizhu** [binpash/hs#91]
```
wget http://mirrors.syringanetworks.net/gnu/emacs/emacs-29.2.tar.xz
tar xf emacs-29.2.tar.gz
cd emacs-29.2
/path/to/spec-spec.sh configure
```

log: https://bns.sh/i.txt (expires in 30d)

```
sh: 24: Syntax error: Missing '))'
ERROR|2024-03-01 15:48:08,139|Parsing error: ParseError
Traceback (most recent call last):
  File "/srv/hs/parallel-orch/analysis.py", line 24, in parse_shell_to_asts
    for untyped_ast, _original_text, _linno_before, _linno_after, in new_ast_objects:
  File "/srv/hs/deps/pash/python_pkgs/libdash/parser.py", line 74, in parse
    raise ParsingException()
libdash.parser.ParsingException: ParseError
```

configure script is POSIX compat (works on dash and no errors on shellcheck)

(tested on fix-conditional)

**Comment by ezrizhu** [comment]
Issue still persists with latest main 13fc64ed3d3f696959f34d22a3d6f04b7178e71a
log: http://bns.sh/n.txt
snippet 
```
DEBUG|2024-03-15 21:37:41,827|Parsing: /tmp/pash_JelhhsX//speculative/partial_order//212
sh: 24: Syntax error: Missing '))'
ERROR|2024-03-15 21:37:41,827|Parsing error: ParseError
Traceback (most recent call last):
  File "/srv/hs/parallel-orch/analysis.py", line 24, in parse_shell_to_asts
    for untyped_ast, _original_text, _linno_before, _linno_after, in new_ast_objects:
  File "/srv/hs/deps/pash/python_pkgs/libdash/parser.py", line 74, in parse
    raise ParsingException()
libdash.parser.ParsingException: ParseError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/hs/parallel-orch/scheduler_server.py", line 238, in <module>
    main()
  File "/srv/hs/parallel-orch/scheduler_server.py", line 234, in main
    scheduler.run()
  File "/srv/hs/parallel-orch/scheduler_server.py", line 187, in run
    self.process_next_cmd()
  File "/srv/hs/parallel-orch/scheduler_server.py", line 104, in process_next_cmd
    self.handle_init(input_cmd)
  File "/srv/hs/parallel-orch/scheduler_server.py", line 82, in handle_init
    self.partial_program_order = util.parse_partial_program_order_from_file(partial_order_file)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/hs/parallel-orch/util.py", line 271, in parse_partial_program_order_from_file
    cmd, asts = parse_cmd_from_file(file_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/hs/parallel-orch/util.py", line 194, in parse_cmd_from_file
    asts = analysis.parse_shell_to_asts(file_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/hs/parallel-orch/analysis.py", line 31, in parse_shell_to_asts
    exit(1)
    ^^^^
NameError: name 'exit' is not defined
PaSh Preprocessor:  Preprocessing -- Unparsing time: 101.164  ms
PaSh:  Preprocessed script stored in: /tmp/pash_JelhhsX/tmpbvm18ac6
PaSh:  Executing: PASH_TMP_PREFIX=/tmp/pash_JelhhsX/ pash_shell_name=configure /usr/bin/env bash +a -c source /tmp/pash_JelhhsX/tmpbvm18ac6 configure
nc: /tmp/pash_spec/pash_b1Ob6xB//scheduler_socket: Connection refused
PaSh:  ----------------------------------------
```
